Shop/Areas/Admin/Controllers/HoaDonController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class HoaDonController : Controller
    {
        // GET: Admin/HoaDon
        public ActionResult Index(int ?id)
        {
            if(id == null)
            {
                return RedirectToAction("Index", new { id = 1 });
            }
            ViewBag.list = Models.HoaDonBus.HoaDonBus.List((int)id);
            return View();
        }
        public ActionResult Edit(string mahd)
        {
            ViewBag.chitiet = Models.HoaDonBus.HoaDonBus.ListCT(mahd);
            var hoadon = Models.HoaDonBus.HoaDonBus.Gethd(mahd);
            return View(hoadon);
        }
        [HttpPost]
        public ActionResult Edit(shop.HOADON hd)
        {
            Models.HoaDonBus.HoaDonBus.Update(hd);
            return RedirectToAction("Edit", new { mahd= hd.MaHoaDon });
        }
        public ActionResult Changes(string mahd, int khoa)
        {
            Models.HoaDonBus.HoaDonBus.Lock(mahd, khoa);
            return RedirectToAction("Index",new { id=khoa});
        }
    }
}

Shop/Areas/Admin/Controllers/NhaSanXuatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class NhaSanXuatController : Controller
    {
       
        // GET: Admin/NhaSanXuat
        public ActionResult Index()
        {
            var nhasanxuat = Models.NhaSanXuatBus.NhaSanXuatBus.List();
            ViewBag.dsnsx = nhasanxuat;
            return View();
        }

        // GET: Admin/NhaSanXuat/Details/5
       
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/NhaSanXuat/Create
       
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/NhaSanXuat/Create
        [HttpPost]
        public ActionResult Create(shop.NHASANXUAT nsx)
        {
            try
            {
                // TODO: Add insert logic here
                Models.NhaSanXuatBus.NhaSanXuatBus.Insert(nsx);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/NhaSanXuat/Edit/5
       
        public ActionResult Edit(int id)
        {
            return View(Models.NhaSanXuatBus.NhaSanXuatBus.Get(id));
        }

        // POST: Admin/NhaSanXuat/Edit/5
        [HttpPost]
        public ActionResult Edit(shop.NHASANXUAT nsx)
        {
            try
            {
                // TODO: Add update logic here
               Models.NhaSanXuatBus.NhaSanXuatBus.UpdateNSX(nsx);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/NhaSanXuat/Delete/5
       
        public ActionResult Delete(int id,int khoa)
        {
            Models.NhaSanXuatBus.NhaSanXuatBus.Lock(id, khoa);
            return RedirectToAction("Index");
        }

        // POST: Admin/NhaSanXuat/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Shop/Areas/Admin/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Shop.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SanPhamController : Controller
    {
        [Authorize(Roles ="Admin")]
        // GET: Admin/SanPham

        public ActionResult Index()
        {
            var List = Models.SanPhamBus.SanPhamBus.List();
            ViewBag.list = List;
            return View();
        }
       
        public ActionResult Create()
        {
            var LoaiSanPham = Models.LoaiSanPham.LoaiSanPhamBus.Listlsp();
            ViewBag.dslsp = LoaiSanPham;
            var NhaSanXuat = Models.NhaSanXuatBus.NhaSanXuatBus.Listnsx();
            ViewBag.dsnsx = NhaSanXuat;
            return View();
        }

        // POST: Admin/SanPham/Create
        [HttpPost, ValidateInput(false)]
        public ActionResult Create(shop.SANPHAM sp)
        {
         
            string pathValue = Server.MapPath("~/");

            var hpt = HttpContext.Request.Files[0];
            if (HttpContext.Request.Files.Count > 0)
            {
                if (hpt.ContentLength > 0)
                {
                    string temp = hpt.FileName;
                    string RDString = Guid.NewGuid().ToString();
                    string fullNameImage = "img/" + RDString + temp;
                    hpt.SaveAs(pathValue + fullNameImage);
                    sp.HinhAnh = fullNameImage;
					Models.SanPhamBus.SanPhamBus.insert(sp);
                }
            }

            return RedirectToAction("Create");

        }
       
        // GET: Admin/SanPham/Edit/5
        public ActionResult Edit(int id)
        {
            var LoaiSanPham = Models.LoaiSanPham.LoaiSanPhamBus.List();
            ViewBag.dslsp = LoaiSanPham;
            var NhaSanXuat = Models.NhaSanXuatBus.NhaSanXuatBus.List();
            ViewBag.dsnsx = NhaSanXuat;
            return View(Models.SanPhamBus.SanPhamBus.GetProduct(id));
        }

        // POST: Admin/SanPham/Edit/5
        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(shop.SANPHAM sp1)
        {
            string pathValue = Server.MapPath("~/");

            var hpt = HttpContext.Request.Files[0];
            if (hpt.FileName =="")
            {
                Models.SanPhamBus.SanPhamBus.UpdateProduct(sp1, 0);
            }
            else
            {
                if (HttpContext.Request.Files.Count > 0)
                {
                    if (hpt.ContentLength > 0)
                    {
                        string temp = hpt.FileName;
                        string RDString = Guid.NewGuid().ToString();
                        string fullNameImage = "img/" + RDString + temp;
                        hpt.SaveAs(pathValue + fullNameImage);
                        sp1.HinhAnh = fullNameImage;
                    }
                }
                Models.SanPhamBus.SanPhamBus.UpdateProduct(sp1, 1);
            }
            return RedirectToAction("Index");
        }


        public ActionResult Delete(int id,int khoa)
        {
            Models.SanPhamBus.SanPhamBus.Lock(id,khoa);
            return RedirectToAction("Index");
        }
        public ActionResult Top()
        {
            ViewBag.top = Models.SanPhamBus.SanPhamBus.Top();
            return View();
        }
    }
}

Shop/Areas/Admin/Controllers/TaiKhoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TaiKhoanController : Controller
    {
        // GET: Admin/TaiKhoan
        public ActionResult Index()
        {
            ViewBag.listacc = Models.TaiKhoanBus.TaiKhoanBus.List();
            return View();
        }
    }
}

Shop/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Shop/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
@{
    ViewBag.Title = "_LayoutAdmin";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <title>LongHaLan</title>

    <!-- Bootstrap Core CSS -->
    <link href="~/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="~/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="~/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="~/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- DataTables CSS -->
    <link href="~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="~/bower_components/datatables-responsive/css/dataTables.responsive.css" rel="stylesheet">

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">LongHaLan</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-cube fa-fw"></i>Sản phẩm<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("Index","SanPham")">List SP</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Create","SanPham")">Add SP</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Top","SanPham")">Top SP</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Loại SP<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("Index","LoaiSanPham")">List</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Create","LoaiSanPham")">Add</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        
                        <li>
                            <a href="#"><i class="fa fa-area-chart fa-fw"></i>Nhà Sản Xuất<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("Index","NhaSanXuat")">List NSX</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Create","NhaSanXuat")">Add NSX</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                         <li>
                            <a href="#"><i class="fa fa-users fa-fw"></i>Người dùng<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("Index","TaiKhoan")">List User</a>
                                </li>
                                <li>
                                    <a href="#">Add User</a>
                                </li>
                            </ul>

                        </li>
                        <li>
                            <a href="#"><i class="fa fa-shopping-cart fa-fw"></i>Hóa Đơn<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("Index","HoaDon",new { id = 1})">Chờ Duyệt</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index","HoaDon",new { id = 2})">Đang Giao</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index","HoaDon",new { id = 3})">Đã Thanh Toán</a>
                                </li>
                            </ul>

                        </li>  
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                @RenderBody()
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="~/bower_components/jquery/dist/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="~/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/bower_components/metisMenu/dist/metisMenu.min.js"></script>
    <script type="text/javascript" src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: '.tinymce',
            height: 500,
            theme: 'modern',
            plugins: [
              'advlist autolink lists link image charmap print preview hr anchor pagebreak',
              'searchreplace wordcount visualblocks visualchars code fullscreen',
              'insertdatetime media nonbreaking save table contextmenu directionality',
              'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc'
            ],
            toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
            toolbar2: 'print preview media | forecolor backcolor emoticons | codesample',
            image_advtab: true,
            
        });
    </script>
    <!-- Custom Theme JavaScript -->
    <script src="~/dist/js/sb-admin-2.js"></script>

    <!-- DataTables JavaScript -->
    <script src="~/bower_components/DataTables/media/js/jquery.dataTables.min.js"></script>
    <script src="~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });
    </script>
</body>

</html>