Shop/Areas/Admin/Controllers/LoaiSanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LoaiSanPhamController : Controller
    {
        // GET: Admin/LoaiSanPham
       
        public ActionResult Index()
        {
            var LoaiSanPham = Models.LoaiSanPham.LoaiSanPhamBus.List();
            ViewBag.dslsp = LoaiSanPham;
            return View();
        }

        // GET: Admin/LoaiSanPham/Details/5
       
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/LoaiSanPham/Create
       
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/LoaiSanPham/Create
        [HttpPost]
        public ActionResult Create(shop.LOAISANPHAM lsp )
        {
            try
            {
                // TODO: Add insert logic here
                Models.LoaiSanPham.LoaiSanPhamBus.insert(lsp);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/LoaiSanPham/Edit/5
       
        public ActionResult Edit(int id)
        {
            
            return View(Models.LoaiSanPham.LoaiSanPhamBus.GetCategory(id));
        }

        // POST: Admin/LoaiSanPham/Edit/5
        [HttpPost]
        public ActionResult Edit(shop.LOAISANPHAM lsp)
        {
            try
            {
                // TODO: Add update logic here
                Models.LoaiSanPham.LoaiSanPhamBus.UpdateCategory(lsp);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/LoaiSanPham/Delete/5
       
        public ActionResult Delete(int id,int khoa)
        {
            Models.LoaiSanPham.LoaiSanPhamBus.Lock(id,khoa);
            return RedirectToAction("Index");
        }

        // POST: Admin/LoaiSanPham/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Shop/Areas/Admin/Views/LoaiSanPham/Create.cshtml
@{
    ViewBag.Title = "Create";
}
@using (Html.BeginForm("Create", "LoaiSanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Loại Sản Phẩm
            <small>Thêm mới loại sp</small>
        </h1>
    </div>
    <!-- /.col-lg-12 -->
    <div class="col-lg-7" style="padding-bottom:120px">
        

            <div class="form-group">
                <label>Têm loại sản phẩm</label>
                <input class="form-control" name="TenLoaiSanPham" placeholder="Tên Loại sp" />
            </div>

            <button type="submit" class="btn btn-default">Thêm loại sản phẩm</button>
            <button type="reset" class="btn btn-default">Reset</button>
           
    </div>
</div>
}

Shop/Areas/Admin/Views/LoaiSanPham/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

Shop/Areas/Admin/Views/LoaiSanPham/Details.cshtml
@{
    ViewBag.Title = "Details";
}

Shop/Areas/Admin/Views/LoaiSanPham/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm("Edit", "LoaiSanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Cập nhật
            <small>loại sản phẩm</small>
        </h1>
    </div>
    <!-- /.col-lg-12 -->
    <div class="col-lg-7" style="padding-bottom:120px">


        <div class="form-group">
            <label>Tên</label>
            <input class="form-control" name="TenLoaiSanPham" value="@Model.TenLoaiSanPham" />
        </div>
        <input type="hidden" name="MaLoaiSanPham" value="@Model.MaLoaiSanPham" />
        <button type="submit" class="btn btn-default">Cập nhật</button>
        <button type="reset" class="btn btn-default">Reset</button>

    </div>
</div>
}

Shop/Areas/Admin/Views/LoaiSanPham/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Loại Sản Phẩm
            <small>Danh sách</small>
        </h1>
    </div>
    <!-- /.col-lg-12 -->
    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
        <thead>
            <tr align="center">
                <th>ID</th>
                <th>Name</th>
                <th>Trạng thái</th>
                <th>Delete</th>
                <th>Edit</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.dslsp)
            {
                <tr class="odd gradeX" align="center">
                    <td>@item.MaLoaiSanPham</td>
                    <td>@item.TenLoaiSanPham</td>
                    @if(@item.TrangThaiLSP==1)
                    { 
                        <td>Mở</td>
                        <td class="center"><i class="fa fa-trash-o  fa-fw"></i><a href="@Url.Action("Delete", "LoaiSanPham", new { id = item.MaLoaiSanPham, khoa =1 })">Khóa</a></td>
                    }
                    else
                    {
                    <td>Khóa</td>
                    <td class="center"><i class="fa fa-trash-o  fa-fw"></i><a href="@Url.Action("Delete", "LoaiSanPham", new { id = item.MaLoaiSanPham, khoa =0 })">Mở khóa</a></td>
                    }                    
                    
                    <td class="center"><i class="fa fa-pencil fa-fw"></i> <a href="@Url.Action("Edit", "LoaiSanPham", new { id=item.MaLoaiSanPham })">Edit</a></td>
                </tr>
            }
           
            
        </tbody>
    </table>
</div>