Shop/Controllers/ProductController.cs
using System;
using Shop.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop.Models.BinhLuanBus;

namespace Shop.Controllers
{
    public class ProductController : Controller
    {
        // GET: SanPham
        public ActionResult Index()
        {
            ViewBag.TopView = Models.SanPhamBus.SanPhamBus.List();
            ViewBag.TopSell = Models.SanPhamBus.SanPhamBus.List2();
            return View();
        }
        public ActionResult LoaiSP(int id, int page = 1)
        {
            var list = Models.SanPhamBus.SanPhamBus.LoaiSP(page, 6, id);

            return View(list);
        }
        public ActionResult NSX(int id, int page = 1)
        {
            var list = Models.SanPhamBus.SanPhamBus.NSX(page, 6, id);

            return View(list);
        }

        // GET: SanPham/Details/5
        public ActionResult Details(int id)
        {
            ViewBag.ListComments = BinhLuanBus.ListComments(id);
            return View(Models.SanPhamBus.SanPhamBus.GetProduct(id));
        }
        public ActionResult Search(string tim, int page = 1)
        {
            var list = Models.SanPhamBus.SanPhamBus.TimKiem(page, 6, tim);
            return View(list);
        }

        // GET: SanPham/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SanPham/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: SanPham/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SanPham/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: SanPham/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SanPham/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Shop/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using shop;
using Microsoft.AspNet.Identity;
namespace Shop.Controllers
{
    public class ShoppingCartController : Controller
    {
        // GET: ShoppingCart
        public ActionResult Index()
        {
            if (Session["cart"] != null)
            {
                ViewBag.tongtien = TongTien();
            }
            return View();
        }
        private int isExit(int id)
        {
            List<Items> cart = (List<Items>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Sp.MaSanPham == id)
                {
                    return i;
                }
            }
            return -1;

        }
        private float TongTien()
        {
            List<Items> cart = (List<Items>)Session["cart"];
            float tongtien = 0;
            for (int i = 0; i < cart.Count; i++)
            {
                tongtien = tongtien + (float)(cart[i].Sp.GiamGia * cart[i].Soluong);
            }
            return tongtien;

        }

        public ActionResult Them(int id,int soluong)
        {
            SANPHAM sp = Models.SanPhamBus.SanPhamBus.GetProduct(id);
            if (Session["cart"]==null)
            {
                if(soluong <= 0)
                {
                    return RedirectToAction("Index");
                }
                List<Items> cart = new List<Items>();
                Items temp = new Items(sp, soluong);
                cart.Add(temp);
                Session["cart"] = cart;
            }
            else
            {
                List<Items> cart = (List<Items>)Session["cart"];
                int result = isExit(id);
                if (result == -1)
                {
                    if (soluong <= 0)
                    {
                        return RedirectToAction("Index");
                    }
                    Items temp = new Items(sp, soluong);
                    cart.Add(temp);
                }
                else
                {
                    if ((cart[result].Soluong + soluong) <= 0)
                    {
                        return RedirectToAction("Xoa",new { id = id});
                    }
                    cart[result].Soluong = cart[result].Soluong + soluong;
                    
                }
                Session["cart"] = cart;
            }
            return RedirectToAction("Index");
        }
        public ActionResult Update(int id, int soluong)
        {
            SANPHAM sp = Models.SanPhamBus.SanPhamBus.GetProduct(id);
            if (Session["cart"] == null)
            {
                if (soluong <= 0)
                {
                    return RedirectToAction("Index");
                }
                List<Items> cart = new List<Items>();
                Items temp = new Items(sp, soluong);
                cart.Add(temp);
                Session["cart"] = cart;
            }
            else
            {
                List<Items> cart = (List<Items>)Session["cart"];
                int result = isExit(id);
                if (result == -1)
                {
                    if (soluong <= 0)
                    {
                        return RedirectToAction("Index");
                    }
                    Items temp = new Items(sp, soluong);
                    cart.Add(temp);
                }
                else
                {
                    if (soluong <= 0)
                    {
                        return RedirectToAction("Xoa", new { id = id });
                    }
                    cart[result].Soluong = soluong;

                }
                Session["cart"] = cart;
            }
            return RedirectToAction("Index");
        }
        public ActionResult Xoa(int id)
        {
            List<Items> cart = (List<Items>)Session["cart"];
            int result = isExit(id);
           
            cart.RemoveAt(result);
            if(cart.Count==0)
            {
                Session["cart"] = null;
            }
            else
            {
                Session["cart"] = cart;
            }
            return RedirectToAction("Index");
        }
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.name = User.Identity.Name;
            if (Session["cart"]==null)
            {
                return RedirectToAction("Index");
            }
            ViewBag.tongtien = TongTien();
            return View();
        }
        [HttpPost]
        public ActionResult Create(string diachi)
        {
            if(diachi=="")
            { return View(); }
            string time = DateTime.Now.ToString("ssmmhhddMMyyyy");
            string id = User.Identity.GetUserId();
            string MaHD = time + id;
            float tongtien= TongTien();
            Models.GioHangBus.GioHangBus.inserthd(MaHD,id,tongtien,diachi);
            List<Items> cart = (List<Items>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
            {
                Models.GioHangBus.GioHangBus.insertchitiet(MaHD, cart[i]);
            }
            Session["cart"] = null;
            return RedirectToAction("Index");
        }

    }
}

Shop/Views/ShoppingCart/Create.cshtml
@using Shop.Controllers;
@{
    ViewBag.Title = "Create";
}

<h2>Chào bạn @User.Identity.Name !</h2>
<h4>Xin hãy nhập thông tin nơi nhận của bạn để chúng tôi có thể liên lạc với bạn:</h4><br/>

@using (Html.BeginForm("Create", "ShoppingCart", FormMethod.Post))
{
    <textarea rows="4" cols="50" name="diachi"></textarea>
    <input type="submit" value="Gửi">
}

<section id="cart_items">
    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">Shopping Cart</li>
        </ol>
    </div>
    <div class="table-responsive cart_info">
        <table class="table table-condensed">
            <thead>
                <tr class="cart_menu">
                    <td class="image" width="100">Item</td>
                    <td class="description"></td>
                    <td class="price">Price</td>
                    <td class="quantity">Quantity</td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                @foreach (Items item in (List<Items>)Session["cart"])
                {
                    <tr>
                        <td class="cart_product">
                            <a href="@Url.Action("Details","Product", new { id = @item.Sp.MaSanPham})"><img src="~/@item.Sp.HinhAnh" alt="" width="30%" height="30%"></a>
                        </td>
                        <td class="cart_description">
                            <h4><a href="">@item.Sp.TenSanPham</a></h4>
                        </td>
                        <td class="cart_price">
                            <p>$@item.Sp.GiamGia</p>
                        </td>
                        <td class="cart_quantity">
                            <h4>@item.Soluong</h4>
                        </td>
                        <td class="cart_total">
                            <p class="cart_total_price">$@(item.Sp.GiamGia * item.Soluong)</p>
                        </td>
                        
                    </tr>
                }
                <tr>
                    <td colspan="3">&nbsp;</td>
                    <td colspan="2">
                        <table class="table table-condensed total-result">
                            <tbody>
                                <tr class="shipping-cost">
                                    <td>Tiền ship</td>
                                    <td>Free</td>
                                </tr>
                                <tr>
                                    <td>Tổng tiền</td>
                                    <td><span>$@ViewBag.tongtien</span></td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>


            </tbody>
        </table>

    </div>

</section>

Shop/Views/ShoppingCart/Index.cshtml
@using Shop.Controllers;
@{
    ViewBag.Title = "Index";
}

@if (Session["cart"] == null)
{
    
        <div class="breadcrumbs">
            <ol class="breadcrumb">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li class="active">Shopping Cart</li>
            </ol>
        </div>
    <h1>Giỏ hàng rỗng</h1><br/>
    <h3>Vui lòng thêm sản phẩm!</h3>
}
else
{
        <section id="cart_items">
                <div class="breadcrumbs">
                    <ol class="breadcrumb">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li class="active">Shopping Cart</li>
                    </ol>
                </div>
                <div class="table-responsive cart_info">
                    <table class="table table-condensed">
                        <thead>
                            <tr class="cart_menu">
                                <td class="image" width="100">Item</td>
                                <td class="description"></td>
                                <td class="price">Price</td>
                                <td class="quantity">Quantity</td>
                                <td class="total">Total</td>
                                <td></td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Items item in (List<Items>)Session["cart"])
                            {
                                <tr>
                                    <td class="cart_product">
                                        <a href="@Url.Action("Details","Product", new { id = @item.Sp.MaSanPham})"><img src="~/@item.Sp.HinhAnh" alt="" width="30%" height="30%"></a>
                                    </td>
                                    <td class="cart_description">
                                        <h4><a href="">@item.Sp.TenSanPham</a></h4>
                                    </td>
                                    <td class="cart_price">
                                        <p>$@item.Sp.GiamGia</p>
                                    </td>
                                    <td class="cart_quantity">
                                        <div class="cart_quantity_button">
                                           
                                            @using (Html.BeginForm("Update", "ShoppingCart", FormMethod.Post))
                                            {
                                                <input type="hidden" name="id" value="@item.Sp.MaSanPham" />
                                                <input class="cart_quantity_input" type="text" name="soluong" value="@item.Soluong" autocomplete="off" size="2" />
                                                <button type="submit" class="btn btn-fefault cart">
                                                    <i class="fa fa-shopping-cart"></i>
                                                    Update
                                                </button>
                                            }
                                        </div>
                                    </td>
                                    <td class="cart_total">
                                        <p class="cart_total_price">$@(item.Sp.GiamGia * item.Soluong)</p>
                                    </td>
                                    <td class="cart_delete">
                                        <a class="cart_quantity_delete" href="@Url.Action("Xoa","ShoppingCart", new { id = @item.Sp.MaSanPham})"><i class="fa fa-times"></i></a>
                                    </td>
                                </tr>
                            }
                            <tr>
                                <td colspan="4">&nbsp;</td>
                                <td colspan="2">
                                    <table class="table table-condensed total-result">
                                        <tbody>
                                            <tr class="shipping-cost">
                                                <td>Tiền ship</td>
                                                <td>Free</td>
                                            </tr>
                                            <tr>
                                                <td>Tổng tiền</td>
                                                <td><span>$@ViewBag.tongtien</span></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>


                        </tbody>
                    </table>
 
                </div>
            <a href="@Url.Action("Create","ShoppingCart")" class="btn btn-fefault cart" text-align="right"><i class="fa fa-shopping-cart"></i>
                Đặt hàng</a>
                
        </section>
        }