Shop/Models/ProductType/ProductType.cs
using shop;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PetaPoco;
namespace Shop.Models.ProductType
{
    public class ProductType
    {

        public static IEnumerable<LOAISANPHAM> danhsachlsp()
        {
            var db = new shopDB();
            return db.Query<LOAISANPHAM>("select * from loaisanpham where TrangThaiLSP = 1");
        }
        public static IEnumerable<NHASANXUAT> danhsachnsx()
        {
            var db = new shopDB();
            return db.Query<NHASANXUAT>("select * from NHASANXUAT where TrangThaiNSX = 1");
        }


    }
    
}

Shop/Controllers/BinhLuanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace Shop.Controllers
{
    public class BinhLuanController : Controller
    {
        // GET: BinhLuan
        [Authorize]
        public ActionResult Create(int MaSanPham, String NoiDung)
        {
            Shop.Models.BinhLuanBus.BinhLuanBus.insert(NoiDung, MaSanPham, User.Identity.Name);
            return RedirectToAction("Details", "Product", new { id = MaSanPham });
        }
    }
}

Shop/Controllers/ProductController.cs
using System;
using Shop.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop.Models.BinhLuanBus;

namespace Shop.Controllers
{
    public class ProductController : Controller
    {
        // GET: SanPham
        public ActionResult Index()
        {
            ViewBag.TopView = Models.SanPhamBus.SanPhamBus.List();
            ViewBag.TopSell = Models.SanPhamBus.SanPhamBus.List2();
            return View();
        }
        public ActionResult LoaiSP(int id, int page = 1)
        {
            var list = Models.SanPhamBus.SanPhamBus.LoaiSP(page, 6, id);

            return View(list);
        }
        public ActionResult NSX(int id, int page = 1)
        {
            var list = Models.SanPhamBus.SanPhamBus.NSX(page, 6, id);

            return View(list);
        }

        // GET: SanPham/Details/5
        public ActionResult Details(int id)
        {
            ViewBag.ListComments = BinhLuanBus.ListComments(id);
            return View(Models.SanPhamBus.SanPhamBus.GetProduct(id));
        }
        public ActionResult Search(string tim, int page = 1)
        {
            var list = Models.SanPhamBus.SanPhamBus.TimKiem(page, 6, tim);
            return View(list);
        }

        // GET: SanPham/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SanPham/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: SanPham/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SanPham/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: SanPham/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SanPham/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Shop/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using shop;
using Microsoft.AspNet.Identity;
namespace Shop.Controllers
{
    public class ShoppingCartController : Controller
    {
        // GET: ShoppingCart
        public ActionResult Index()
        {
            if (Session["cart"] != null)
            {
                ViewBag.tongtien = TongTien();
            }
            return View();
        }
        private int isExit(int id)
        {
            List<Items> cart = (List<Items>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Sp.MaSanPham == id)
                {
                    return i;
                }
            }
            return -1;

        }
        private float TongTien()
        {
            List<Items> cart = (List<Items>)Session["cart"];
            float tongtien = 0;
            for (int i = 0; i < cart.Count; i++)
            {
                tongtien = tongtien + (float)(cart[i].Sp.GiamGia * cart[i].Soluong);
            }
            return tongtien;

        }

        public ActionResult Them(int id,int soluong)
        {
            SANPHAM sp = Models.SanPhamBus.SanPhamBus.GetProduct(id);
            if (Session["cart"]==null)
            {
                if(soluong <= 0)
                {
                    return RedirectToAction("Index");
                }
                List<Items> cart = new List<Items>();
                Items temp = new Items(sp, soluong);
                cart.Add(temp);
                Session["cart"] = cart;
            }
            else
            {
                List<Items> cart = (List<Items>)Session["cart"];
                int result = isExit(id);
                if (result == -1)
                {
                    if (soluong <= 0)
                    {
                        return RedirectToAction("Index");
                    }
                    Items temp = new Items(sp, soluong);
                    cart.Add(temp);
                }
                else
                {
                    if ((cart[result].Soluong + soluong) <= 0)
                    {
                        return RedirectToAction("Xoa",new { id = id});
                    }
                    cart[result].Soluong = cart[result].Soluong + soluong;
                    
                }
                Session["cart"] = cart;
            }
            return RedirectToAction("Index");
        }
        public ActionResult Update(int id, int soluong)
        {
            SANPHAM sp = Models.SanPhamBus.SanPhamBus.GetProduct(id);
            if (Session["cart"] == null)
            {
                if (soluong <= 0)
                {
                    return RedirectToAction("Index");
                }
                List<Items> cart = new List<Items>();
                Items temp = new Items(sp, soluong);
                cart.Add(temp);
                Session["cart"] = cart;
            }
            else
            {
                List<Items> cart = (List<Items>)Session["cart"];
                int result = isExit(id);
                if (result == -1)
                {
                    if (soluong <= 0)
                    {
                        return RedirectToAction("Index");
                    }
                    Items temp = new Items(sp, soluong);
                    cart.Add(temp);
                }
                else
                {
                    if (soluong <= 0)
                    {
                        return RedirectToAction("Xoa", new { id = id });
                    }
                    cart[result].Soluong = soluong;

                }
                Session["cart"] = cart;
            }
            return RedirectToAction("Index");
        }
        public ActionResult Xoa(int id)
        {
            List<Items> cart = (List<Items>)Session["cart"];
            int result = isExit(id);
           
            cart.RemoveAt(result);
            if(cart.Count==0)
            {
                Session["cart"] = null;
            }
            else
            {
                Session["cart"] = cart;
            }
            return RedirectToAction("Index");
        }
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.name = User.Identity.Name;
            if (Session["cart"]==null)
            {
                return RedirectToAction("Index");
            }
            ViewBag.tongtien = TongTien();
            return View();
        }
        [HttpPost]
        public ActionResult Create(string diachi)
        {
            if(diachi=="")
            { return View(); }
            string time = DateTime.Now.ToString("ssmmhhddMMyyyy");
            string id = User.Identity.GetUserId();
            string MaHD = time + id;
            float tongtien= TongTien();
            Models.GioHangBus.GioHangBus.inserthd(MaHD,id,tongtien,diachi);
            List<Items> cart = (List<Items>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
            {
                Models.GioHangBus.GioHangBus.insertchitiet(MaHD, cart[i]);
            }
            Session["cart"] = null;
            return RedirectToAction("Index");
        }

    }
}

Shop/Views/Product/Details.cshtml
@{
    ViewBag.Title = "Details";
}
    <div class="product-details">
        <!--product-details-->
        <div class="col-sm-5">
            <div class="view-product">
                <img src="~/@Model.HinhAnh" alt="">
                <h3>ZOOM</h3>
            </div>
            <div id="similar-product" class="carousel slide" data-ride="carousel">

                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    <div class="item active left">
                        <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                        <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                        <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                    </div>
                    <div class="item next left">
                        <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                        <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                        <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                    </div>
                    <div class="item">
                        <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                        <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                        <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                    </div>

                </div>

                <!-- Controls -->
                <a class="left item-control" href="#similar-product" data-slide="prev">
                    <i class="fa fa-angle-left"></i>
                </a>
                <a class="right item-control" href="#similar-product" data-slide="next">
                    <i class="fa fa-angle-right"></i>
                </a>

            </div>
            




        </div>
        <div class="col-sm-7">
            <div class="product-information">
                <!--/product-information-->
                <img src="~/images/product-details/new.jpg" class="newarrival" alt="">
                <h2>@Model.TenSanPham</h2>               
                <img src="~/images/product-details/rating.png" alt="">
                <br />
                <span>
                    <h4>Giá :<s>@Model.Gia</s></h4>
                    <h2>Giá Sốc:</h2><span>@Model.GiamGia</span>
                    <br />
                    <label>View : @Model.SoLuongXem</label>
                    <label>Số lượng</label>
                @using (Html.BeginForm("Them", "ShoppingCart", FormMethod.Post))
                    {
                    <input type="hidden" name="id" value="@Model.MaSanPham"/>
                    <input type="text" value="1" name="soluong">
                    <button type="submit" class="btn btn-fefault cart">
                        <i class="fa fa-shopping-cart"></i>
                        Thêm vào giỏ
                    </button>
                   }
                </span>
                <p><b>Availability:</b> Còn Hàng</p>
                <p><b>Condition:</b> New</p>
                <p><b>Brand:</b> Shop LongHaLan</p>
                <a href=""><img src="~/images/product-details/share.png" class="share img-responsive" alt=""></a>
            </div><!--/product-information-->
        </div>
    </div>
<div class="col-sm-8">
    <div class="warp-comments">
        <h2>Bình Luận</h2>
        @using (Html.BeginForm("Create", "BinhLuan", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <input name="MaSanPham" value="@Model.MaSanPham" type="hidden" />
                    @Html.TextArea("NoiDung")
                    <button type="submit" class="btn btn-success">Gửi</button>
        }
        <div class="conments">
            @foreach (var item in ViewBag.ListComments)
            {
                <div class="comment-name">
                    @item.MaTaiKhoan
                </div>
                        <div class="comments-content" style="text-align:right;">
                            @item.NoiDung
                        </div>
            }

        </div>
    </div><!--/product-details-->
 </div>

Shop/Views/Product/Index.cshtml
@model IEnumerable<shop.SANPHAM>

<div class="row">
    <h2 class="title text-center">Sản Phẩm Xem Nhiều nhất</h2>
    @foreach (var item in ViewBag.TopView)
    {
        <div class="col-sm-4">
            <div class="product-image-wrapper">
                <div class="single-products">
                    <div class="productinfo text-center">
                        <a href="@Url.Action("Details", "Product", new { id=item.MaSanPham })"><img src="~/@item.HinhAnh" alt="" height="360px"></a>
                        <h2>@item.GiamGia</h2>
                        <p>@item.TenSanPham</p>
                        @using (Html.BeginForm("Them", "ShoppingCart", FormMethod.Post))
                        {
                            <input type="hidden" name="id" value="item.MaSanPham" />
                            <input type="hidden" name="soluong" value="1" />
                            <button class="btn btn-default add-to-cart" type="submit">
                                <i class="fa fa-shopping-cart"></i>Thêm vào giỏ
                            </button>

                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>
    <div class="row">
        <h2 class="title text-center">Sản Phẩm Xem Nhiều nhất</h2>
        @foreach (var item in ViewBag.TopSell)
        {
            <div class="col-sm-4">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <a href="@Url.Action("Details", "Product", new { id=item.MaSanPham })"><img src="~/@item.HinhAnh" alt="" height="360px"></a>
                            <h2>@item.GiamGia</h2>
                            <p>@item.TenSanPham</p>
                            @using (Html.BeginForm("Them", "ShoppingCart", FormMethod.Post))
                            {
                                <input type="hidden" name="id" value="item.MaSanPham" />
                                <input type="hidden" name="soluong" value="1" />
                                <button class="btn btn-default add-to-cart" type="submit">
                                    <i class="fa fa-shopping-cart"></i>Thêm vào giỏ
                                </button>

                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

Shop/Views/Product/LoaiSP.cshtml
@model PetaPoco.Page<shop.SANPHAM>

        <!--features_items-->
        <h2 class="title text-center">Sản phẩm đặc sắc</h2>
        @foreach (var item in Model.Items)
            {
            <div class="col-sm-4">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <a href="@Url.Action("Details", "Product", new { id=item.MaSanPham })"><img src="~/@item.HinhAnh" alt="" height="360px"></a>
                            <h2>@item.GiamGia</h2>
                            <p>@item.TenSanPham</p>
                            <a href="@Url.Action("Them","ShoppingCart",new { id = @item.MaSanPham,soluong = 1})" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Thêm vào giỏ</a>
                        </div>

                        <div class="choose">
                            <ul class="nav nav-pills nav-justified">
                                <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                                <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        }
        <div class="col-sm-12" align="center">
            <ul class="pagination">
                @if (Model.CurrentPage > 1)
            {
                    <li><a href="@Url.Action("LoaiSP", "Product", new { Page = Model.CurrentPage - 1})"><span class="fa fa-angle-left"></span> Prev</a></li>
                }
                @for (int i = 1; i <= Model.TotalPages; i++)
            {
                if (i == Model.CurrentPage)
                {
                        <li class="active"><a href="@Url.Action("LoaiSP", "Product", new { Page = i})">@i</a></li>
                    }
                    else
                    {
                        <li><a href="@Url.Action("LoaiSP", "Product", new { Page = i})">@i</a></li>
                    }

                }

                @if (Model.CurrentPage < Model.TotalPages)
            {
                    <li><a href="@Url.Action("LoaiSP", "Product", new { Page = Model.CurrentPage + 1})">Next <span class="fa fa-angle-right"></span></a></li>
                }
            </ul>
        </div>

Shop/Views/Product/NSX.cshtml
@model PetaPoco.Page<shop.SANPHAM>


        <!--features_items-->
        <h2 class="title text-center">Sản phẩm đặc sắc</h2>
        @foreach (var item in Model.Items)
            {
            <div class="col-sm-4">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <a href="@Url.Action("Details", "Product", new { id=item.MaSanPham })"><img src="~/@item.HinhAnh" alt="" height="360px"></a>
                            <h2>@item.GiamGia</h2>
                            <p>@item.TenSanPham</p>
                            <a href="@Url.Action("Them","ShoppingCart",new { id = @item.MaSanPham,soluong = 1})" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Thêm vào giỏ</a>
                        </div>

                        <div class="choose">
                            <ul class="nav nav-pills nav-justified">
                                <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                                <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        }
        <div class="col-sm-12" align="center">
            <ul class="pagination">
                @if (Model.CurrentPage > 1)
            {
                    <li><a href="@Url.Action("NSX", "Product", new { Page = Model.CurrentPage - 1})"><span class="fa fa-angle-left"></span> Prev</a></li>
                }
                @for (int i = 1; i <= Model.TotalPages; i++)
            {
                if (i == Model.CurrentPage)
                {
                        <li class="active"><a href="@Url.Action("NSX", "Product", new { Page = i})">@i</a></li>
                    }
                    else
                    {
                        <li><a href="@Url.Action("NSX", "Product", new { Page = i})">@i</a></li>
                    }

                }

                @if (Model.CurrentPage < Model.TotalPages)
            {
                    <li><a href="@Url.Action("NSX", "Product", new { Page = Model.CurrentPage + 1})">Next <span class="fa fa-angle-right"></span></a></li>
                }
            </ul>
        </div>

Shop/Views/Product/Search.cshtml
@model PetaPoco.Page<shop.SANPHAM>

<!--features_items-->
<h2 class="title text-center">Tìm Kiếm</h2>
@if (Model.Items.Count == 0)
{
    <h1>Không tìm thấy sản phẩm phù hợp</h1>
}
else
{
        foreach (var item in Model.Items)
    {
    <div class="col-sm-4">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <img src="~/@item.HinhAnh" alt="">
                    <h2>@item.GiamGia</h2>
                    <p>@item.TenSanPham</p>
                    <a href="@Url.Action("Them","ShoppingCart",new { id = @item.MaSanPham,soluong = 1})" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Thêm vào giỏ</a>
                </div>

                <div class="choose">
                    <ul class="nav nav-pills nav-justified">
                        <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                        <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    }
    <div class="col-sm-12" align="center">
        <ul class="pagination">
            @if (Model.CurrentPage > 1)
            {
                <li><a href="@Url.Action("Search", "Product", new { Page = Model.CurrentPage - 1})"><span class="fa fa-angle-left"></span> Prev</a></li>
            }
            @for (int i = 1; i <= Model.TotalPages; i++)
            {
                if (i == Model.CurrentPage)
                {
                    <li class="active"><a href="@Url.Action("Search", "Product", new { Page = i})">@i</a></li>
                }
                else
                {
                    <li><a href="@Url.Action("Search", "Product", new { Page = i})">@i</a></li>
                }

            }

            @if (Model.CurrentPage < Model.TotalPages)
            {
                <li><a href="@Url.Action("Search", "Product", new { Page = Model.CurrentPage + 1})">Next <span class="fa fa-angle-right"></span></a></li>
            }
        </ul>
    </div>

}